from PyQt5 import QtCore, QtGui, QtWidgets
#import SCAN, CSCAN, FCFS, SSTF, LOOK, CLOOK
import FCFS, SSTF, SCAN, CSCAN, LOOK, CLOOK

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(847, 649)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(220, 130, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn1.setFont(font)

        self.btn1.clicked.connect(self.FCFS)
        
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(380, 130, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.btn2.setFont(font)

        self.btn2.clicked.connect(self.SSTF)
        
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(540, 130, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.btn3.setFont(font)

        self.btn3.clicked.connect(self.SCAN)
        
        self.btn3.setObjectName("btn3")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(220, 200, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.btn4.setFont(font)

        self.btn4.clicked.connect(self.CSCAN)
        
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(380, 200, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.btn5.setFont(font)

        self.btn5.clicked.connect(self.LOOK)
        
        self.btn5.setObjectName("btn5")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(540, 200, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.btn6.setFont(font)

        self.btn6.clicked.connect(self.CLOOK)
        
        self.btn6.setObjectName("btn6")
        self.l5 = QtWidgets.QLineEdit(self.centralwidget)
        self.l5.setGeometry(QtCore.QRect(150, 550, 113, 20))
        self.l5.setObjectName("l5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 520, 61, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 50, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 350, 47, 13))
        self.label_3.setObjectName("label_3")
        self.l3 = QtWidgets.QLineEdit(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(150, 370, 511, 21))
        self.l3.setObjectName("l3")
        self.l1 = QtWidgets.QLineEdit(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(150, 320, 113, 20))
        self.l1.setObjectName("l1")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 300, 91, 16))
        self.label_4.setObjectName("label_4")
        self.l2 = QtWidgets.QLineEdit(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(330, 320, 113, 20))
        self.l2.setObjectName("l2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(330, 300, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(370, 270, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(350, 420, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.l4 = QtWidgets.QLineEdit(self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(150, 480, 501, 20))
        self.l4.setObjectName("l4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(150, 450, 61, 21))
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 847, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "D7C - 70,71,72"))
        self.btn1.setText(_translate("MainWindow", "FCFS"))
        self.btn2.setText(_translate("MainWindow", "SSTF"))
        self.btn3.setText(_translate("MainWindow", "SCAN"))
        self.btn4.setText(_translate("MainWindow", "C-SCAN"))
        self.btn5.setText(_translate("MainWindow", "LOOK"))
        self.btn6.setText(_translate("MainWindow", "C-LOOK"))
        self.label.setText(_translate("MainWindow", "SEEK TIME"))
        self.label_2.setText(_translate("MainWindow", "DISK SCHEDULING ALGORITHM SIMULATOR"))
        self.label_3.setText(_translate("MainWindow", "Requests"))
        self.label_4.setText(_translate("MainWindow", "No. of requests"))
        self.label_5.setText(_translate("MainWindow", "Head start"))
        self.label_6.setText(_translate("MainWindow", "INPUTS"))
        self.label_7.setText(_translate("MainWindow", "OUTPUT"))
        self.label_8.setText(_translate("MainWindow", "Sequence"))

    def FCFS(self):
        n = self.l1.text()
        disk = self.l2.text()
        d = self.l3.text()
        sum = 0
        FCFS.main(n,disk,d,sum)
        self.l5.setText(str(sum))

    def SSTF(self):
        n = self.l1.text()
        disk = self.l2.text()
        d = self.l3.text()
        sum = 0
        SSTF.main(n,disk,d,sum)
        self.l5.setText(str(sum))

    def SCAN(self):
        n = self.l1.text()
        disk = self.l2.text()
        d = self.l3.text()
        sum = 0
        SCAN.main(n,disk,d,sum)
        self.l5.setText(str(sum))

    def CSCAN(self):
        n = self.l1.text()
        disk = self.l2.text()
        d = self.l3.text()
        sum = 0
        CSCAN.main(n,disk,d,sum)
        self.l5.setText(str(sum))

    def LOOK(self):
        n = self.l1.text()
        disk = self.l2.text()
        d = self.l3.text()
        sum = 0
        LOOK.main(n,disk,d,sum)
        self.l5.setText(str(sum))

    def CLOOK(self):
        n = self.l1.text()
        disk = self.l2.text()
        d = self.l3.text()
        sum = 0
        CLOOK.main(n,disk,d,sum)
        self.l5.setText(str(sum))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
